kind = "mobile"
previewPath = "/mobile/"
title = "Ledger Mobile"
version = "1.0.0"
id = "artifacts/ledger-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 19309

[services.development]
run = "pnpm --filter @workspace/ledger-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ledger-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ledger-mobile", "run", "serve" ]

[services.env]
PORT = "19309"
BASE_PATH = "/mobile/"
