// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/file-upload/FileUpload.tsx": () => import("../components/mockups/file-upload/FileUpload.tsx"),
  "./components/mockups/planner-layouts/AdvisorReport.tsx": () => import("../components/mockups/planner-layouts/AdvisorReport.tsx"),
  "./components/mockups/planner-layouts/BentoDashboard.tsx": () => import("../components/mockups/planner-layouts/BentoDashboard.tsx"),
  "./components/mockups/planner-layouts/ControlCockpit.tsx": () => import("../components/mockups/planner-layouts/ControlCockpit.tsx")
};
