// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/file-upload/FileUpload.tsx": () => import("../components/mockups/file-upload/FileUpload.tsx"),
  "./components/mockups/planner-layouts/AdvisorReport.tsx": () => import("../components/mockups/planner-layouts/AdvisorReport.tsx"),
  "./components/mockups/planner-layouts/BentoDashboard.tsx": () => import("../components/mockups/planner-layouts/BentoDashboard.tsx"),
  "./components/mockups/planner-layouts/ControlCockpit.tsx": () => import("../components/mockups/planner-layouts/ControlCockpit.tsx"),
  "./components/mockups/planner-usability/AccessibleReadable.tsx": () => import("../components/mockups/planner-usability/AccessibleReadable.tsx"),
  "./components/mockups/planner-usability/AffordanceForward.tsx": () => import("../components/mockups/planner-usability/AffordanceForward.tsx"),
  "./components/mockups/planner-usability/HierarchyFirst.tsx": () => import("../components/mockups/planner-usability/HierarchyFirst.tsx"),
  "./components/mockups/planner-variants/ComparisonCockpit.tsx": () => import("../components/mockups/planner-variants/ComparisonCockpit.tsx"),
  "./components/mockups/planner-variants/GoalFirstAssistant.tsx": () => import("../components/mockups/planner-variants/GoalFirstAssistant.tsx"),
  "./components/mockups/planner-variants/OutcomeNarrative.tsx": () => import("../components/mockups/planner-variants/OutcomeNarrative.tsx")
};
